# Generated by Django 5.1.6 on 2025-02-18 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='androidapp',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='android_apps/'),
        ),
    ]
