# Generated by Django 5.1.6 on 2025-02-18 15:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0002_androidapp_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='androidapp',
            name='points',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
