# Generated by Django 5.1.6 on 2025-02-19 05:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0003_alter_androidapp_points'),
    ]

    operations = [
        migrations.RenameField(
            model_name='completedtask',
            old_name='com',
            new_name='complete_at',
        ),
    ]
