# Generated by Django 5.1.6 on 2025-02-19 05:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0004_rename_com_completedtask_complete_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='completedtask',
            old_name='complete_at',
            new_name='completed_at',
        ),
    ]
